name: ðŸ› Bug report
description: Report a bug currently impacting tsml-eval.
title: "[BUG] "
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: >
      #### You can see if he bug has already been addressed by searching
      through the open and closed [issues](https://github.com/time-series-machine-learning/tsml-eval/issues?q=is%3Aissue).
- type: textarea
  attributes:
    label: Describe the bug
    description: >
      A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps/Code to reproduce the bug
    description: |
      Please include a [minimal reproducible example](https://stackoverflow.com/help/mcve) so users can reproduce the error when running it. Be as succinct as possible, and do not depend on external data files.

      If the code is too long, feel free to put it in a public [gist](https://gist.github.com) and link it in the issue.
    placeholder: |
      ```python
      Your code here. placing your code between three backticks will format it like the above example.
      ```
- type: textarea
  attributes:
    label: Expected results
    description: >
      Please provide a clear and concise description of the expected results or paste the correct output if available.
    placeholder: >
      For example: No error is thrown, or y_name1 == y_name2.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual results
    description: |
      Please provide a clear and concise description of the actual seen results or paste the incorrect output if available.

      If you observe an error, please paste the error message including the full traceback of the exception. For instance the code example above raises the following exception:
    placeholder: |
      ```python-traceback
      Place traceback error here if applicable. If your issue has no traceback, please describe the observed output without formatting.
      ```
  validations:
    required: true
