name: PR Typecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "tsml_eval/**"
      - "pyproject.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install tsml-eval, dependencies and mypy
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[all_extras,unstable_extras,dev] mypy

      - name: Show dependencies
        run: python -m pip list

      - name: Run mypy typecheck
        run: mypy tsml_eval/
